spring:
  application:
    name: NEXORA-BACKEND
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://username:password@localhost:27017/nexora?authSource=admin}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  Kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_BROKERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: reactive-audit-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    listener:
      ack-mode: manual

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: nexora
              uri: http://localhost:9001
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=1

server:
  port: ${PORT:9001}

app:
  security:
    un-secured-path:
      - "/identity/accounts/users/register"
      - "/identity/accounts/users/authenticate"
      - "/identity/sessions/validate"
      - "/identity/sessions/refresh"
      - "/users/register"
    jwt:
      secret: ${JWT_SECRET:secret}
  zone:
    base-url: ${ZONE_BASE_URL:http://localhost:${server.port}}
  feed:
    base-url: ${FEED_BASE_URL:http://localhost:${server.port}}
  automation:
    feed-base-url: ${FEED_BASE_URL:http://localhost:${server.port}}
  identity:
    user-base-url: ${USER_BASE_URL:http://localhost:${server.port}}
